# Site settings
title: Ocupop
email: dev@ocupop.com
description: ''
url: "https://chartreuse-echidna.cloudvent.net/"
permalink: pretty
analytics_code:

# Collections
collections:
  projects:
    output: true
    layout: project
    permalink: /work/:path/

# defaults:
#   - 
#     scope:
#       type: 'examples'
#     values:
#       layout: default
#       variable_name: value

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-lunr-js-search

# feed:
#   title: Client Name
#   description: Description of feed
#   url: primary url
#   path: alternate path

categories:
  - Branding
  - Strategy
  - Web
  - Events
  - Presentation
  - Illustration
  - Animation
