# Site settings
title: Ocupop
email: dev@ocupop.com
description: 'A small super-powered creative agency with zero awards'
url: "https://ocupop.com/"
permalink: pretty
analytics_code: UA-20780270-1

placeholders:
  hero: /assets/img/1800x800.png
  aspect-4x3: /assets/img/768x500.png
  aspect-1x1: /assets/img/768x768.png

socialshare:
  featured_image: assets/img/socialshare.png
  twitter:
    username: '@Ocupop'
    image:

# Collections
collections:
  projects:
    output: true
    layout: project
    permalink: /work/:path/
  focuses:
    output: true
    layout: focus
    permalink: /focus/:title/

# defaults:
#   -
#     scope:
#       type: 'examples'
#     values:
#       layout: default
#       variable_name: value

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap

# feed:
#   title: Client Name
#   description: Description of feed
#   url: primary url
#   path: alternate path

tags:
  - branding
  - strategy
  - web
  - events
  - presentation
  - illustration
  - animation

project_statuses:
  - active
  - draft
  - private
  - featured
