source: src
timezone: America/Chicago
markdown:
  engine: commonmark
  options: {}

paths:
  data: data
  static: ''
  uploads: uploads

collections_config:
  pages:
    path: content/pages
    name: Pages
    icon: wysiwyg
    url: '/[full_slug]/'
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        icon: note_add
        schema: default
    schemas:
      default:
        path: schemas/page_schema.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Page
        icon: notes
        new_preview_url: /
  projects:
    path: content/projects
    name: Projects
    icon: work
    _enabled_editors:
      - visual
    add_options:
    - name: Add New Project
      icon: note_add
      schema: default
    schemas:
      default:
        path: schemas/project_schema.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Case Study
        icon: notes
        # new_preview_url: /
  services:
    path: content/services
    name: Services
    icon: design_services
    disable_url: true
    schemas:
      default:
        path: schemas/service_schema.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Service
        icon: notes
  team_members:
    path: content/team_members
    name: Team Members
    icon: group
    disable_url: true
    schemas:
      default:
        path: schemas/team_member_schema.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Team Member
        icon: notes
  data:
    path: data
    name: Data
    icon: important_devices
    disable_add: true
    disable_add_folder: true

_structures:
  example:
    values:
      - value:
          name:
          description:
          image:

_select_data:
  work_tags:
    - User Research
    - Market Strategy
    - Brand Identity

_inputs:
  layout:
    type: auto
    hidden: true
    cascade: true
  service_tags:
    type: multiselect
    options:
      values: _select_data.work_tags