import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
			'sans': ['commuters-sans', 'system-ui', 'sans-serif'],
      'serif': ["'Berlingske Serif Regular'", 'serif']
		},
    extend: {
      screens: {
        'sm': '640px',     // Small devices (phones)
        'md': '768px',     // Medium devices (tablets)
        'lg': '1024px',    // Large devices (laptops)
        'xl': '1280px',    // Extra large (desktops)
        '2xl': '1536px',   // 2X large displays
        '3xl': '1920px',   // Full HD displays
        '4xl': '2560px',   // 2K / QHD displays
        '5xl': '3840px',   // 4K / UHD displays
			},
      maxWidth: {
        '8xl': '96rem',     // 1536px
        '9xl': '120rem',    // 1920px
        '10xl': '160rem',    // 2560px
        '11xl': '190rem',    // 3040px
        '12xl': '220rem',    // 3520px
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        'dark': '#1F2528',
				'mid': {
					100: '#EFF3F7',
					200: '#DCE1E6',
					300: '#C3C7CB',
					400: '#9DA0A4',
					500: '#7B7E80',
					600: '#67696B',
					700: '#494949',
					800: '#303132',
					900: '#1D1D1F',
					DEFAULT: '#F3F1EE'
				},
        'light': '#E8E1D8',
        'bittercube': '#17384B',

      },
    },
  },
  safelist: [
    'bg-bittercube',
    'bg-[#F7F1DB]',
    'bg-dark',
    'bg-light',
    'bg-white',
    'rounded-sm',
    'rounded-md',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-3xl',
    'rounded-4xl',
    'rounded-none',
    'pb-2',
    'pb-4',
    'pb-6',
    'pb-8',
    'pb-10',
    'pb-12',
    'pb-16',
    'pb-20',
    'pb-28',
    'pb-36',
    'pt-2',
    'pt-4',
    'pt-6',
    'pt-8',
    'pt-10',
    'pt-12',
    'pt-16',
    'pt-20',
    'pt-28',
    'pt-36',
    'py-2',
    'py-4',
    'py-6',
    'py-8',
    'py-10',
    'py-12',
    'py-16',
    'py-20',
    'py-28',
    'py-36',
    'px-2',
    'px-4',
    'px-6',
    'px-8',
    'px-10',
    'px-12',
    'px-16',
    'px-20',
    'px-28',
    'px-36',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'sm:grid-cols-1',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'sm:grid-cols-4',
    'sm:grid-cols-5',
    'sm:grid-cols-6',
    'md:grid-cols-1',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'md:grid-cols-5',
    'md:grid-cols-6',
    'lg:grid-cols-1',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'lg:grid-cols-5',
    'lg:grid-cols-6',
    'xl:grid-cols-1',
    'xl:grid-cols-2',
    'xl:grid-cols-3',
    'xl:grid-cols-4',
    'xl:grid-cols-5',
    'xl:grid-cols-6',
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-5',
    'col-span-6',
    'sm:col-span-1',
    'sm:col-span-2',
    'sm:col-span-3',
    'sm:col-span-4',
    'sm:col-span-5',
    'sm:col-span-6',
    'md:col-span-1',
    'md:col-span-2',
    'md:col-span-3',
    'md:col-span-4',
    'md:col-span-5',
    'md:col-span-6',
    'lg:col-span-1',
    'lg:col-span-2',
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-5',
    'lg:col-span-6',
    'xl:col-span-1',
    'xl:col-span-2',
    'xl:col-span-3',
    'xl:col-span-4',
    'xl:col-span-5',
    'xl:col-span-6',

  ],
  plugins: [],
} satisfies Config;
